project:
  type: book

book:
  title: "Lorem-ipsum-2.github.io"
  author: "Norah Jones"
  date: "6/26/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



